name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: javac *.java
