name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build Project
      - run: javac -cp "junit-4.10.jar:." *.java

  calcadd:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Add
        run: |
          javac -cp "junit-4.10.jar:." *.java
          javac -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestAdd

  calcsub:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Sub
        run: |
          javac -cp "junit-4.10.jar:." *.java
          javac -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestSub

  calcdiv:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Div
        run: |
          javac -cp "junit-4.10.jar:." *.java
          javac -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestDiv

  calcmul:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Calculator Mul
        run: |
          javac -cp "junit-4.10.jar:." *.java
          javac -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestMul